#! /usr/bin/python

level_1 =[
"PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
"P                                                                                                                                                                                                                                                                                                                                                                                          P",
"P                                                                                                                                                                                                                                                                                                                                                                                          P",
"P                                                                                                                                                                                                                                                                                                                                                                                          P",
"P                                                                                                                                                                                                                                                                                                                                                                                          P",
"P                                                                                                                                                                                                                                                                                                                                                                                          P",
"P                                      P                                                                                                                                                                                                                                                                                                                                                   P",
"P                         P     P  PPP  PP P               PPPP                                                                                                                                                                                                                                                                                                                            P",
"P                     P                     P      PPPPPP        PP                               E                                                                                                                                                                                                                                                                                        P",
"P                                             PPP                   PPPP                   PPPPP                                                                                                                                                                                                                                                                                           P",
"P                 P                                                      PPPP        PPPP                                                                                                                                                                                                                                                                                                  P",
"PPPPPPPPPPPPPPPPPPP    P PPPPPPPPPPPP                                          PPPPP            PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP"]
